---
# Check for the variable “docker_opts” which is not defined by default,
# and if it is defined will add the options defined in the variable to the file:
- name: Configure Docker
  template:
      src=default_docker.j2
      dest=/etc/default/docker
      mode=0644
      owner=root
      group=root
  notify: restart docker
