---
- name: git clone https://github.com/home1-oss/docker-privoxy.git
  git:
    repo: https://github.com/home1-oss/docker-privoxy.git
    dest: /tmp/docker-privoxy
    force: yes
    update: yes
    version: "{{ branch }}"

- name: docker-compose up docker-privoxy
  docker_service:
    build: no
    files: docker-compose.yml
    project_src: /tmp/docker-privoxy
    pull: yes
    remove_volumes: no
