---
- name: Installing and configuring Docker
  hosts: raw
  vars:
    create_oss_network: yes
    install_docker_compose: yes
    install_docker_machine: yes
  roles:
  - { role: home1-oss.oss-docker-install, tags: ["docker"] }

- name: Docker config
  hosts: raw
  vars:
    docker_insecure_registries:
    - registry.docker.internal
    - mirror.docker.internal
    - gcr.io.internal:25004
    docker_registry_mirrors:
    - http://mirror.docker.internal
  roles:
    - { role: home1-oss.oss-docker-config, tags: ["docker-config"] }

- name: Setup /etc/resolv.conf
  hosts: raw
  vars:
    resolv_conf_nameservers:
    - "{{ hostvars['net']['ansible_ssh_host'] }}"
    - "{{ forwarders }}"
    - 8.8.4.4
    - 8.8.8.8
    #resolv_conf_search_domains:
    #- example.com
  roles:
  - { role: kbrebanov.resolv_conf, tags: ["dns"] }

- hosts: "net"
  vars:
    service: rawhost1
    service_ip: "{{ hostvars['rawhost1']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns"] }
- hosts: "net"
  vars:
    service: rawhost2
    service_ip: "{{ hostvars['rawhost2']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns"] }
- hosts: "net"
  vars:
    service: rawhost3
    service_ip: "{{ hostvars['rawhost3']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns"] }
