# -*- mode: ruby -*-
# vi: set ft=ruby :

INIT_SH_PATH = File.join(File.dirname(__FILE__), "vagrant_assets/init.sh")
SYSCTL_CONF_PATH = File.join(File.dirname(__FILE__), "vagrant_assets/sysctl.conf")

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  #config.ssh.private_key_path = ["#{ENV['HOME']}/.vagrant.d/insecure_private_key","#{ENV['HOME']}/.ssh/id_rsa"]
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" # avoids 'stdin: is not a tty' error.

  config.vm.box_check_update = false
  config.vm.box= "chshawkn/ubuntu1604"

  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: "true"

  N = 3
  (1..N).each do |machine_id|
    config.vm.define "rawhost#{machine_id}" do |machine|
      machine.vm.hostname = "rawhost#{machine_id}"
      machine.vm.network "forwarded_port", guest: 22, host: 60050+machine_id, auto_correct: true
      #machine.vm.network "private_network", ip: "172.22.101.#{50+machine_id}", netmask: "255.255.255.0", nic_type: "82545EM"
      machine.vm.network "public_network", ip: "192.168.199.#{50+machine_id}", netmask: "255.255.255.0", nic_type: "82545EM"

      machine.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--name", "rawhost#{machine_id}"]
      end
    end
  end

  if File.exist?(SYSCTL_CONF_PATH)
    config.vm.provision :file, :source => "#{SYSCTL_CONF_PATH}", :destination => "/tmp/sysctl.conf"
    config.vm.provision :shell, :privileged => true, :inline => "if [[ -f /tmp/sysctl.conf ]]; then mv /tmp/sysctl.conf /etc/sysctl.conf; sysctl -p; fi"
  end
  if File.exist?(INIT_SH_PATH)
    config.vm.provision :file, :source => "#{INIT_SH_PATH}", :destination => "/tmp/init.sh"
    config.vm.provision :shell, :privileged => true, :inline => "chmod 755 /tmp/init.sh"
    config.vm.provision :shell, :privileged => true, :inline => "/tmp/init.sh"
  end

  config.vm.provision "shell", run: "always", inline: <<-SCRIPT
    eval `route -n | awk '{ if ($8 =="eth0" && $2 != "0.0.0.0") print "route del default gw " $2; }'`
    eval `route -n | awk '{ if ($8 =="enp0s3" && $2 != "0.0.0.0") print "route del default gw " $2; }'`
    #eval `route -n | awk '{ if ($8 =="eth1" && $2 != "0.0.0.0") print "route del default gw " $2; }'`

    route add default gw 192.168.199.1 || echo route of default gw 192.168.199.1 already exists
    #route -A inet6 add default gw fc00::1 eth2
  SCRIPT
end
