---
- name: docker-gitlab
  docker_service:
    project_name: docker-gitlab
    definition:
      version: '2.1'
      services:
        gitlab:
          image: home1oss/gitlab:9.1.4-ce.0
          restart: always
          container_name: ${GIT_HOSTNAME:-gitlab.internal}
          hostname: ${GIT_HOSTNAME:-gitlab.internal}
          ports:
          - "${GITLAB_SHELL_SSH_PORT:-20022}:${GITLAB_SHELL_SSH_PORT:-20022}"
          - "${GIT_HTTP_PORT:-10080}:${GIT_HTTP_PORT:-10080}"
          volumes:
          - volume-gitlab-git_volume:${GIT_VOLUME:-/app/gitlab/data}
          #- ../../:${GIT_VOLUME:-/app/gitlab/data}/workspace
          # keep gitlab's data
          - volume-gitlab-data:/data
          - volume-gitlab-etc_gitlab:/etc/gitlab
          - volume-gitlab-var_log_gitlab:/var/log/gitlab
          - volume-gitlab-var_opt_gitlab:/var/opt/gitlab
          environment:
          - CONFIGSERVER_WEBHOOK_ENDPOINT=${CONFIGSERVER_WEBHOOK_ENDPOINT:-http://configserver.internal:8888/monitor}
          - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-user_pass}
          - GITLAB_SHELL_SSH_PORT=${GITLAB_SHELL_SSH_PORT:-20022}
          - GIT_ADMIN_USERNAME=${GIT_ADMIN_USERNAME:-user}
          - GIT_DEPLOY_KEY=${GIT_DEPLOY_KEY:-/app/gitlab/data/default_deploy_key.pub}
          - GIT_HOSTNAME=${GIT_HOSTNAME:-gitlab.internal}
          - GIT_HTTP_PORT=${GIT_HTTP_PORT:-10080}
          - GIT_VOLUME=${GIT_VOLUME:-/app/gitlab/data}
          - GIT_WORKSPACE=${GIT_VOLUME:-/app/gitlab/data}/workspace
          - SKIP_AUTO_REPO_INIT=${SKIP_AUTO_REPO_INIT:-false}
      networks:
        default:
          external:
            name: oss-network
      volumes:
        volume-gitlab-data: {}
        volume-gitlab-etc_gitlab: {}
        volume-gitlab-git_volume: {}
        volume-gitlab-var_log_gitlab: {}
        volume-gitlab-var_opt_gitlab: {}
