---
- connection: local
  hosts: all

  roles:
  - role: geerlingguy.homebrew
    tags: ['homebrew']
  - role: geerlingguy.dotfiles
    when: configure_dotfiles
    tags: ['dotfiles']

  vars_files:
  - default.config.yml

  tasks:
  - include: tasks/ansible-setup.yml

  - include: tasks/sudoers.yml
    when: configure_sudoers

  - include: tasks/terminal.yml
    when: configure_terminal

  - include: tasks/osx.yml
    when: configure_osx
    tags: ['osx']

  - name: install nodejs
    # nvm is not compatible with the npm config "prefix" option
    # `npm config delete prefix` or `nvm use --delete-prefix v6.11.0`
    shell: . /usr/local/opt/nvm/nvm.sh && nvm install 6.11.0 || nvm use --delete-prefix v6.11.0 --silent

  - name: fix https://github.com/ansible/ansible-modules-extras/issues/2128
    shell: ln -fs /usr/local/opt/nvm/versions/node/v6.11.0/bin/npm /usr/local/bin/npm; ln -fs /usr/local/opt/nvm/versions/node/v6.11.0/bin/node /usr/local/bin/node

  - include: tasks/extra-packages.yml
    tags: ['extra-packages']

  - name: Run configured post-provision ansible task files.
    include: "{{ outer_item }}"
    loop_control:
      loop_var: outer_item
    with_fileglob: "{{ post_provision_tasks|default(omit) }}"
