---
- connection: local
  hosts: all

  roles:
  - role: geerlingguy.homebrew
    tags: ['homebrew']

  vars:
    homebrew_installed_packages:
    - groovy

  vars_files:
  - default.config.yml

  tasks:
  - include: tasks/ansible-setup.yml

  - include: tasks/sudoers.yml
    when: configure_sudoers

  - include: tasks/terminal.yml
    when: configure_terminal

  - include: tasks/osx.yml
    when: configure_osx
    tags: ['osx']

  - include: tasks/extra-packages.yml
    tags: ['extra-packages']

  - name: Run configured post-provision ansible task files.
    include: "{{ outer_item }}"
    loop_control:
      loop_var: outer_item
    with_fileglob: "{{ post_provision_tasks|default(omit) }}"
