---
- connection: local
  hosts: all

  roles:
  - role: geerlingguy.homebrew
    tags: ['homebrew']
  - role: geerlingguy.dotfiles
    when: configure_dotfiles
    tags: ['dotfiles']

  vars:
    homebrew_installed_packages:
    - ant # Java 1.8+ is required
    - gflags@2.2.0
    - groovy
    - gradle # Java 1.7+ is required
    - libsodium@1.0.12
    - lz4@1.7.5
    - openssl@1.1.0.e
    - rocksdb_f201a44
    - scala
    - sbt
    - snappy@1.1.4
    - sqlite@3.18.0

    homebrew_cask_apps:
    - android-ndk14b
    - android-sdk25

  vars_files:
  - default.config.yml

  tasks:
  - include: tasks/ansible-setup.yml

  - include: tasks/sudoers.yml
    when: configure_sudoers

  - include: tasks/terminal.yml
    when: configure_terminal

  - include: tasks/osx.yml
    when: configure_osx
    tags: ['osx']

  - name: install nodejs
    shell: . /usr/local/opt/nvm/nvm.sh && nvm install 6.11.0 && nvm use --delete-prefix v6.11.0

  - include: tasks/extra-packages.yml
    tags: ['extra-packages']

  - name: Run configured post-provision ansible task files.
    include: "{{ outer_item }}"
    loop_control:
      loop_var: outer_item
    with_fileglob: "{{ post_provision_tasks|default(omit) }}"
