---
- name: git clone https://github.com/home1-oss/docker-nexus3.git
  git:
    repo: https://github.com/home1-oss/docker-nexus3.git
    dest: /tmp/docker-nexus3
    force: yes
    update: yes
    version: "{{ branch }}"

- name: docker-compose up docker-nexus3
  docker_service:
    build: no
    files: docker-compose.yml
    project_src: /tmp/docker-nexus3
#    pull: yes
    remove_volumes: no
