---
- name: git clone {{ repo }}
  git:
    repo: "{{ git_repo }}"
    dest: "{{ git_dest }}"
    force: yes
    update: yes
    version: "{{ branch }}"

- name: "docker-compose up docker-proxy/{{ file }}"
  docker_service:
    build: "{{ build | default(no) }}"
    files: "{{ file | default(docker-compose.yml) }}"
    project_src: "{{ git_dest }}"
    pull: "{{ pull | default(yes) }}"
    remove_volumes: "{{ remove_volumes | default(no) }}"
