---
- name: git clone {{ git_repo }}
  git:
    repo: "{{ git_repo }}"
    dest: "{{ git_dest }}"
    force: yes
    update: yes
    version: "{{ branch }}"

- name: docker-compose up {{ file }}
  docker_service:
    build: no # "{{ build | default(False) }}"
    files: "{{ file | default('docker-compose.yml') }}"
    project_src: "{{ git_dest }}"
    pull: yes #"{{ pull | default(True) }}"
    remove_volumes: "{{ remove_volumes | default(False) }}"
