---
- name: git clone https://github.com/home1-oss/docker-proxy.git
  git:
    repo: https://github.com/home1-oss/docker-proxy.git
    dest: /tmp/docker-proxy
    force: yes
    update: yes
    version: "{{ branch }}"

- name: "docker-compose up docker-proxy/{{ file }}"
  docker_service:
    build: no
    files: "{{ file }}"
    project_src: /tmp/docker-proxy
#    pull: yes
    remove_volumes: no
