---
- name: Setup /etc/resolv.conf
  hosts: ["cloud"]
  vars:
    resolv_conf_nameservers:
    - "{{ hostvars['net']['ansible_ssh_host'] }}"
    - 8.8.4.4
    - 8.8.8.8
    #resolv_conf_search_domains:
    #- example.com
  roles:
  - { role: kbrebanov.resolv_conf, tags: ["always"] }

- name: Installing and configuring Docker
  hosts: cloud
  sudo: yes
  roles:
  - { role: home1-oss.oss-docker-install, tags: ["docker"] }

- name: Docker config
  hosts: cloud
  sudo: yes
  roles:
  - { role: home1-oss.oss-docker-config, tags: ["docker-config"] }

- hosts: "net"
  vars:
    service: rancherhost1
    service_ip: "{{ hostvars['rancherhost1']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns"] }
- hosts: "net"
  vars:
    service: rancherhost2
    service_ip: "{{ hostvars['rancherhost2']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns"] }
- hosts: "net"
  vars:
    service: rancherhost3
    service_ip: "{{ hostvars['rancherhost3']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns"] }

- name: Setting up Rancher Server
  hosts: "rancherserver"
  sudo: yes
  roles:
  - { role: rancher_server, tags: ["rancher_server"] }
- hosts: "net"
  vars:
    service: rancherserver
    service_ip: "{{ hostvars['rancherserver']['ansible_ssh_host'] }}"
  roles:
  - { role: oss-dns-record, tags: ["dns", "rancher_server"] }

- name: Register Rancher Hosts
  hosts: "{{ hosts | default('hosts') }}"
  sudo: yes
  roles:
  - { role: rancher_reg, tags: ["rancher_reg"] }
