---
- name: Installing and configuring Docker
  hosts: all
  sudo: yes
  roles:
    - { role: home1-oss.oss-docker-install, tags: ["docker"] }

#- name: Installing and configuring Docker
#  hosts: all
#  sudo: yes
#  roles:
#    - { role: oss-docker-install, tags: ["docker"] }

- name: Docker config
  hosts: all
  sudo: yes
  roles:
    - { role: home1-oss.oss-docker-config, tags: ["docker-config"] }

#- name: Docker config
#  hosts: all
#  sudo: yes
#  roles:
#    - { role: oss-docker-config, tags: ["docker-config"] }

- name: Setting up Rancher Server
  hosts: "rancherserver"
  sudo: yes
  roles:
    - { role: rancher_server, tags: ["rancher_server"] }

- name: Register Rancher Hosts
  hosts: "hosts"
  sudo: yes
  roles:
    - { role: rancher_reg, tags: ["rancher_reg"] }
