---
- name: Setup /etc/resolv.conf
  hosts: ["cloud"]
  vars:
    resolv_conf_nameservers:
    - "{{ hostvars['net']['ansible_ssh_host'] }}"
    - 8.8.4.4
    - 8.8.8.8
    #resolv_conf_search_domains:
    #- example.com
  roles:
  - { role: kbrebanov.resolv_conf, tags: ["always"] }

- name: Installing and configuring Docker
  hosts: cloud
  sudo: yes
  roles:
  - { role: home1-oss.oss-docker-install, tags: ["docker"] }

#- name: Installing and configuring Docker
#  hosts: all
#  sudo: yes
#  roles:
#    - { role: oss-docker-install, tags: ["docker"] }

- name: Docker config
  hosts: cloud
  sudo: yes
  roles:
  - { role: home1-oss.oss-docker-config, tags: ["docker-config"] }

#- name: Docker config
#  hosts: cloud
#  sudo: yes
#  roles:
#    - { role: oss-docker-config, tags: ["docker-config"] }

- name: Setting up Rancher Server
  hosts: "rancherserver"
  sudo: yes
  roles:
  - { role: rancher_server, tags: ["rancher_server"] }
- hosts: "net"
  vars:
    service: bind
    service_ip: "{{ hostvars['net']['ansible_ssh_host'] }}"
    roles:
    - { role: oss-dns-record, tags: ["dns"] }

- name: Register Rancher Hosts
  hosts: "{{ hosts | default('hosts') }}"
  sudo: yes
  roles:
  - { role: rancher_reg, tags: ["rancher_reg"] }
