# -*- mode: ruby -*-
# vi: set ft=ruby :

INIT_SH_PATH = File.join(File.dirname(__FILE__), "vagrant_assets/init.sh")
SYSCTL_CONF_PATH = File.join(File.dirname(__FILE__), "vagrant_assets/sysctl.conf")

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#
Vagrant.configure(2) do |config|

  config.ssh.insert_key = false
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'" # avoids 'stdin: is not a tty' error.

  config.vm.box_check_update = false

  config.vm.define "rancherserver" do |rancherserver|
    rancherserver.vm.box= "chshawkn/ubuntu1404"
    rancherserver.vm.hostname = 'rancherserver'

    rancherserver.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: "true"
    rancherserver.vm.network "forwarded_port", guest: 22, host: 60100, auto_correct: true
    #rancherserver.vm.network :private_network, ip: "172.22.101.100", netmask: "255.255.255.0", nic_type: "82545EM"
    rancherserver.vm.network "public_network", ip: "192.168.199.100", netmask: "255.255.255.0", nic_type: "82545EM"

    rancherserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "rancherserver"]
    end
  end

  N = 4
  (1..N).each do |machine_id|
    config.vm.define "rancherhost#{machine_id}" do |machine|
      machine.vm.box= "chshawkn/ubuntu1404"

      if machine_id == 1
        machine.vm.box= "chshawkn/ubuntu1604"
      end
      if machine_id == 2
        machine.vm.box= "chshawkn/centos7"
      end

      machine.vm.hostname = "rancherhost#{machine_id}"
      machine.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: "true"
      machine.vm.network "forwarded_port", guest: 22, host: 60100+machine_id, auto_correct: true
      #machine.vm.network "private_network", ip: "172.22.101.#{100+machine_id}", netmask: "255.255.255.0", nic_type: "82545EM"
      machine.vm.network "public_network", ip: "192.168.199.#{100+machine_id}", netmask: "255.255.255.0", nic_type: "82545EM"

      machine.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["modifyvm", :id, "--memory", 5120]
        v.customize ["modifyvm", :id, "--name", "rancherhost#{machine_id}"]
      end
    end
  end

  config.vm.provision "shell", :privileged => true, inline: "echo whoami $(whoami) pwd $(pwd)"

  if File.exist?(SYSCTL_CONF_PATH)
    config.vm.provision :file, :source => "#{SYSCTL_CONF_PATH}", :destination => "/tmp/sysctl.conf"
    config.vm.provision :shell, :privileged => true, :inline => "if [[ -f /tmp/sysctl.conf ]]; then mv /tmp/sysctl.conf /etc/sysctl.conf; sysctl -p; fi"
  end
  if File.exist?(INIT_SH_PATH)
    config.vm.provision :file, :source => "#{INIT_SH_PATH}", :destination => "/tmp/init.sh"
    config.vm.provision :shell, :privileged => true, :inline => "chmod 755 /tmp/init.sh"
    config.vm.provision :shell, :privileged => true, :inline => "/tmp/init.sh"
  end

  config.vm.provision "shell", run: "always", inline: <<-SCRIPT
    eval `route -n | awk '{ if ($8 =="eth0" && $2 != "0.0.0.0") print "route del default gw " $2; }'`
    eval `route -n | awk '{ if ($8 =="enp0s3" && $2 != "0.0.0.0") print "route del default gw " $2; }'`
    #eval `route -n | awk '{ if ($8 =="eth1" && $2 != "0.0.0.0") print "route del default gw " $2; }'`

    route add default gw 192.168.199.1
    #route -A inet6 add default gw fc00::1 eth2
  SCRIPT
end
